// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID                int32              `json:"id"`
	PhoneNumber       string             `json:"phone_number"`
	Content           string             `json:"content"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ResponseMessageID pgtype.Text        `json:"response_message_id"`
	FailReason        pgtype.Text        `json:"fail_reason"`
	RetryCount        pgtype.Int4        `json:"retry_count"`
}
